name: Deploy Infrastructure (Apply)

# 💡 핵심: push가 아니라 수동 버튼(workflow_dispatch)으로만 실행되게 함!
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. AWS 로그인 (OIDC 사용)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::[내계정번호]:role/[내_OIDC_역할이름]
          aws-region: ap-northeast-2

      # 2. 로봇 컴퓨터에 테라폼 설치
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0" # 본인 버전으로 맞춤

      # 3. 테라폼 초기화 및 생성 (묻지도 따지지도 않고 승인: -auto-approve)
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve